# Generated by Django 4.1.1 on 2022-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100, unique=True)),
                ('Status', models.CharField(max_length=100)),
                ('CreatedBy', models.CharField(max_length=100)),
                ('AssignedTo', models.CharField(max_length=100)),
            ],
        ),
    ]
